authenticate/urls.py
from django.urls import path
from .views import register, login_view


app_name = 'authenticate'
urlpatterns = [
    path('register/', register, name='register'),
    path('authentication/', login_view, name='login')
]

dashboard/urls.py
from django.urls import path
from . views import home, about, contact_us

app_name = 'dashboard'
urlpatterns = [
    path('', home, name='home'),
    path('about/', about, name='about'),
    path('contact_us/', contact_us, name='contact_us'),
]

todoapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls', namespace='dashboard')),
    path('login/', auth_views.LoginView.as_view(template_name='authenticate/login.html'), name='login'),
    path('user/', include('authenticate.urls', namespace='authenticate')),
]

activity/models.py
from django.db import models

# Create your models here.

authenticate/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    is_show = models.BooleanField(default=False)
    image = models.ImageField(default='profile.png', upload_to='profile_pics')
    is_confirm = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

dashboard/models.py
from django.db import models

# Create your models here.

authenticate/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name',
                  'email', 'password1', 'password2']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['is_show', 'image']

activity/views.py
from django.shortcuts import render

# Create your views here.

authenticate/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import signals, authenticate, login
from django.http import JsonResponse, HttpResponse
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import views as auth_views
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from sweet_alert.modal_alert import modal_message
from django.utils.datastructures import MultiValueDictKeyError


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            success_msg = "Your account has been created! You are now able to log in."
            messages.success(
                request, modal_message('success', None, success_msg))
            return redirect('login')
        else:
            messages.error(
                request, modal_message('error', None, "There's roblem while processing your registration.").display_message())
    else:
        form = UserRegisterForm()
    return render(request, 'authenticate/register.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        try:
            username = request.POST['username']
            password = request.POST['password']
            msg_error = ''
            user = authenticate(request, username=username, password=password)

            if user is not None:

                # no activation required
                login(request, user)
                return redirect('home')

                # add this line for email confirmation
                # if user.profile.is_confirm:
                #     login(request, user)
                #     return redirect('home')
                # else:
                #     msg_error = "Please activate your account. We send activation in your email"
                #     messages.error(
                #         request, modal_message('error', None, msg_error).display_message())
            else:
                msg_error = "Username and password didn't match"
                messages.error(
                    request, modal_message('error', None, msg_error).display_message())
        except MultiValueDictKeyError:
            msg_error = "There's a problem in login please try to login again."
            messages.error(
                request, modal_message('error', None, msg_error).display_message())

    return redirect('login')


@ login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()

            messages.success(request, display_message(
                'success', None, 'Your profile has been updated'))
            return redirect(request.META['HTTP_REFERER'])
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }

    return render(request, 'users/profile.html', context)


@ login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, display_message(
                'success', None, 'Your password was successfully updated!'))
            return redirect('users:profile')
        else:

            messages.error(request, display_message(
                'error', None, 'Please correct the error below'))
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'users/change_password.html', {'form': form})


class PasswordResetConfirmView(auth_views.PasswordResetConfirmView):

    success_url = reverse_lazy('password_reset_complete')

    def form_valid(self, form):
        user = form.save()
        reset()
        return super().form_valid(form)


def login_summary(request):
    if request.method == 'GET':
        log_list = AccessLog.objects.filter(username=request.user)

        return render(request, 'users/access_logs.html', {'logs': logs_paginator(log_list, request)})


def login_summary_filter(request):
    if request.method == 'GET':
        attempt_time = request.GET['attempt_time']
        log_list = AccessLog.objects.filter(attempt_time__date=attempt_time)

        context = {
            'logs': logs_paginator(log_list, request),
            'filter_date': attempt_time,
        }
        return render(request, 'users/access_logs.html', context)


def logs_paginator(list, request):
    # paginator settings
    logs = None

    page = request.GET.get('page', 1)
    paginator = Paginator(list, 10)
    try:
        logs = paginator.page(page)
    except PageNotAnInteger:
        logs = paginator.page(1)
    except EmptyPage:
        logs = paginator.page(paginator.num_pages)

    return logs

dashboard/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required


def home(request):

    return render(request, 'dashboard/home.html')


def about(request):

    return render(request, 'dashboard/about.html')


def contact_us(request):

    return render(request, 'dashboard/contact_us.html')

authenticate/templates/authenticate/create_account_modal.html
<!-- Modal Create Account -->
<div class="modal fade" id="createAccountModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="createAccountModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-fullscreen">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="createAccountModalLabel">Create Account</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <div class="d-flex justify-content-center">
                <div class="col-md-6 col-sm-10">
                    <form action="#" method="POST">
                        {% csrf_token %}
                        <div class="form-floating mb-3">
                            <input type="text" class="form-control" id="usernameText" 
                                aria-describedby="usernameHelp" placeholder="input username">
                            <label for="usernameText">Username*</label>
                        </div>
                        <div class="form-floating mb-3">
                            <input type="text" class="form-control" id="firstnameText" 
                                aria-describedby="firstnameHelp" placeholder="input firstname">
                            <label for="firstnameText">First Name*</label>
                        </div>
                        <div class="form-floating mb-3">
                            <input type="text" class="form-control" id="lastnameText" 
                                aria-describedby="lastnameHelp" placeholder="input lastname">
                            <label for="lastnameText">Last Name*</label>
                        </div>
                        <div class="form-floating mb-3">
                            <input type="password" class="form-control" id="passwordText"  placeholder="input password">
                            <label for="passwordText">Password*</label>
                        </div>
                        <div class="form-floating mb-3">
                            <input type="password" class="form-control" id="passwordText"  placeholder="input password">
                            <label for="passwordText">Re-type Password*</label>
                        </div>
                        <div class="d-flex justify-content-center">
                            <button type="submit" class="btn btn-primary btn-lg">Singup</button>
                        </div>    
                    </form>
                </div>
            </div>
        </div>
      </div>
    </div>
  </div>

authenticate/templates/authenticate/login.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block content %}
<div class="row justify-content-center vh-100">
    <div class="col-md-6 col-sm-9 my-auto">
        <div class="card login-form">
            <div class="card-header text-center">
                <p class="fs-2">Login</p> 
            </div>
            <div class="card-body">
                <form action="{% url 'authenticate:login' %}" method="POST">
                    {% csrf_token %}
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control" id="usernameText" 
                            aria-describedby="usernameHelp" name="username" placeholder="input username" required>
                        <label for="usernameText">Username*</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="password" class="form-control" id="passwordText"  
                            placeholder="input password" name="password" required>
                        <label for="passwordText">Password*</label>
                    </div>
                    <div class="mb-3">
                        <a href="{% url 'authenticate:register' %}">Don't have account?</a>
                    </div>
                    <div class="d-flex justify-content-center">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>    
                </form>
            </div>
        </div>
    </div>
</div>

{% include 'authenticate/create_account_modal.html' %}
{% endblock content %}

authenticate/templates/authenticate/register.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-md-6 col-sm-9 col-lg-6 my-auto">
        <div class="card login-form">
            <div class="card-header text-center">
                <p class="fs-2">Register</p> 
            </div>
            <div class="card-body">
                <form action="{% url 'authenticate:register' %}" method="POST">
                    {% csrf_token %}
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control {% if form.errors.username %}is-invalid {% endif %}" id="usernameText" 
                            aria-describedby="usernameHelp" name="username" placeholder="input username" required>
                        <label for="usernameText">Username*</label>
                        <div class="invalid-feedback">
                            Please enter your username.
                        </div>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control" id="firstnameText" 
                            aria-describedby="firstnameHelp" name="first_name" placeholder="input firstname"  required>
                        <label for="firstnameText">First Name</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control" id="lastnameText" 
                            aria-describedby="lastnameHelp" name="last_name" placeholder="input lastname"  required>
                        <label for="lastnameText">Last Name</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="email" class="form-control {% if form.errors.email %}is-invalid {% endif %}" id="emailText" 
                            aria-describedby="emailHelp" name="email" placeholder="input email"  required>
                        <label for="emailText">Email Address*</label>
                        <div class="invalid-feedback">
                            Please enter your email address.
                        </div>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="password" class="form-control {% if form.errors.password1 %}is-invalid {% endif %}" 
                            id="passwordText1"  name="password1" placeholder="input password" required>
                        <label for="passwordText1">Password*</label>
                        <div class="invalid-feedback">
                            Password didn't match!
                        </div>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="password" class="form-control {% if form.errors.password2 %}is-invalid {% endif %}" 
                            id="passwordText2" name="password2" placeholder="input password"  required>
                        <label for="passwordText2">Re-type Password*</label>
                        <div class="invalid-feedback">
                            Please enter your confirmation password.
                        </div>
                    </div>
                    <div class="d-flex justify-content-center">
                        <button type="submit" class="btn btn-primary btn-lg">Signup</button>
                    </div>   
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

dashboard/templates/dashboard/about.html
{% extends 'dashboard/base.html' %}
{% block content %}
<div class="container-sm my-4 vh-100">
    <div class="row border rounded border-5 p-3">
        <div class="col align-self-center mb-4">
            <p class="fs-2 fw-bold">What is todo list app?</p>
            <p class="fs-4">
                Essentially, it is a simple note-taking platform, 
                where you can write all the important to-dos, 
                check the time that you spent in specific category that you do also help you
                to track all of your progress.
            </p>
        </div>
        <div class="col">
            <div class="d-flex justify-content-center">
                <lottie-player src="https://assets4.lottiefiles.com/private_files/lf30_lan9twdz.json"  background="#0D6EDF"  speed="1"  
            class="activity-lottie" hover loop  autoplay></lottie-player>
            </div>
        </div>
        
    </div>
</div>
{% endblock content %}

dashboard/templates/dashboard/base.html
{% load static %}
<!doctype html class="h-100">
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <!-- Fontawesome CSS -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'dashboard/css/login-stlye.css' %}">
    <link rel="stylesheet" href="{% static 'dashboard/css/dark_mode.css' %}">

    <!-- icon -->
    <link rel="icon" href="{% static 'dashboard/todo-icon.svg' %}">
    <title>Todo App</title>

    <style>
      body {
        display: flex !important;
        min-height: 100vh !important;
        flex-direction: column !important;
      }

      main {
        flex: 1 !important;
      }
    </style>
  </head>
  <body class="d-flex flex-column h-100">
    <header>
        <nav class="navbar navbar-expand-md navbar-dark bg-primary">
            <div class="container-fluid">
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
                <!-- <a class="navbar-brand" href="#">
                    <img src="{% static 'dashboard/todo-icon-46.svg' %}" alt="" width="30" height="24" class="d-inline-block align-top">
                </a> -->
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                      <li class="nav-item">
                          <a class="nav-link" href="{% url 'dashboard:home' %}">Home</a>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link" href="#">Reviews</a>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link" href="{% url 'dashboard:contact_us' %}">Contact Us</a>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link" href="{% url 'dashboard:about' %}">About</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                    </ul>
                    <form class="d-flex m-0">
                      <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                      <button class="btn btn-light" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    
    <main class="">
        <div class="container justify-content-center">
            {% block content %}
            {% endblock content %}
        </div>
    </main>
    
    <footer id="contactUs" class="bg-primary text-white text-center text-lg-start">
        <!-- Grid container -->
        <div class="container p-4">
          <!--Grid row-->
          <div class="row">
            <!--Grid column-->
            <div class="col-lg-6 col-md-12 mb-md-0">
              <h5 class="text-uppercase">To Do App</h5>
      
              <p>
                This website is build using <a href="https://getbootstrap.com/"
                 target="_blank" class="text-reset">Bootstrap 5</a> 
                and is power by Python Django Framework.
              </p>
            </div>
            <!--Grid column-->
      
            <!--Grid column-->
            <div class="col-lg-3 col-md-6 mb-md-0">
              <h5 class="text-uppercase">Contact Us</h5>
      
              <ul class="list-unstyled mb-0">
                <li>
                  <a href="mailto:jhonrhayparreno22@gmail.com" class="text-white">jhonrhayparreno22@gmail.com</a>
                </li>
                <li>
                  <a href="https://www.linkedin.com/in/jhon-rhay-parre%C3%B1o-426a93145/" 
                  target="_blank" class="text-white">LinkedIn</a>
                </li>
                <li>
                  <a href="tel:09321764095" class="text-white">(+63) 9321764095</a>
                </li>
              </ul>
            </div>
            <!--Grid column-->
      
            <!--Grid column-->
            <div class="col-lg-3 col-md-6 mb-md-0">
              <h5 class="text-uppercase mb-0">More</h5>
      
              <ul class="list-unstyled">
                <li>
                  <a href="https://github.com/JRParreno" target="_blank" class="text-white">Github</a>
                </li>
              </ul>
            </div>
            <!--Grid column-->
          </div>
          <!--Grid row-->
        </div>
        <!-- Grid container -->
      </footer>
      <div class="position-fixed py-2 px-3 bg-dark text-white rounded-pill" style="bottom:1rem;left:1rem;">
        <div class="form-check form-switch">
          <input class="form-check-input" type="checkbox" id="darkMode">
          <label id="darkModeLabel" for="darkMode">Light</label>
        </div>
        </div>
      {% if messages  %}
      {% for message in messages %}
      <input type="hidden" id="idsplayMessage" value="{{message}}">
      {% endfor %}
      {% endif %}
    <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script> -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    <script src="https://use.fontawesome.com/e532668696.js"></script>
    <!-- Option 2: Separate Popper and Bootstrap JS -->
    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
    <script>
      $(document).ready(function(e){
         var pathname = window.location.pathname;
         atag = $('#navbarToggle a[href="'+pathname+'"]'); 
         atag.addClass("active");
       });
    </script>
    <script>
      $(function () {
          if ($("#idsplayMessage").length == 1) {
              obj = JSON.parse($("#idsplayMessage").val());
              Swal.fire({
                  icon: obj.tags,
                  title: 'System Message',
                  text: obj.message,
                  width: 600,
                  padding: '3em',
                  backdrop: `
                  rgba(0, 0, 0, 0.8)
              `
              })
          }
      })
  </script>
  <script>
    var darkMode = document.getElementById('darkMode');

var darkLabel = "darkModeLabel";
var darkLang = "Dark";
var lightLang = "Light";

var imgID = "logo";
var darkImg = "./dark.png";
var lightImg = "./light.png";

window.addEventListener('load', function () {
  if (darkMode) {
    initTheme();
    darkMode.addEventListener('change', function () {
      resetTheme();
    });
  }
});

function initTheme() {
  var darkThemeSelected = localStorage.getItem('darkMode') !== null && localStorage.getItem('darkMode') === 'dark';
  darkMode.checked = darkThemeSelected;
  darkThemeSelected ? document.body.setAttribute('data-theme', 'dark') : document.body.removeAttribute('data-theme');
}

function resetTheme() {
  if (darkMode.checked) {
    document.body.setAttribute('data-theme', 'dark');
    localStorage.setItem('darkMode', 'dark');
    document.getElementById(imgID).src = darkImg;
    document.getElementById(darkLabel).innerHTML = darkLang;
  } else {
    document.body.removeAttribute('data-theme');
    localStorage.removeItem('darkMode');
    document.getElementById(imgID).src = lightImg;
    document.getElementById(darkLabel).innerHTML = lightLang;
  }
}
  </script>
  </body>
</html>

dashboard/templates/dashboard/contact_us.html
{% extends 'dashboard/base.html' %}
{% block content %}
<div class="container-sm my-4 vh-100">
    <div class="row border rounded border-5 p-3">
        <div class="col align-self-center mb-4">
            <p class="fs-2 fw-bold">Contact Us</p>
            <p class="fs-4">
                <i class="far fa-envelope"></i> <span class="fw-bold text-break">jhonrhayparreno22@gmail.com</span>
            </p>
            <p class="fs-4">
                <i class="far fa-address-card"></i> <span class="fw-bold text-break">(+63) 932 1764 095</span>
            </p>
        </div>
        <div class="col">
            <div class="d-flex justify-content-center">
                <lottie-player src="https://assets6.lottiefiles.com/private_files/lf30_6VfTTj.json"  background="#0D6EFD"  speed="1"  
                class="activity-lottie" hover loop  autoplay></lottie-player>
            </div>
        </div>
        
    </div>
</div>
{% endblock content %}

dashboard/templates/dashboard/home.html
{% extends 'dashboard/base.html' %}
{% block content %}
<div class="container-fuild my-4 vh-100">
    <div class="row row-cols-md-2 row-cols-sm-1 border rounded border-5 p-3">
        <div class="col align-self-center mb-4">
            <p class="fs-1 fw-bold text-uppercase">Welcome to Todo list app website</p>            
        </div>
        <div class="col">
            <div class="d-flex justify-content-center">
                <lottie-player src="https://assets8.lottiefiles.com/packages/lf20_Yfas6J.json"  
                background="#A6B0C3"  speed="1"  class="activity-lottie"  loop  autoplay></lottie-player>
                
            </div>
        </div>
    </div>
</div>

{% endblock content %}